"""Public contract API for bone-imaging derivative datasets."""

from .compatibility import (
    discover_legacy_registered_microarchitecture_records, discover_legacy_timelapsed_records,
    write_compatibility_manifest,
)
from .batch_discovery import (
    BatchArtifact,
    CaseKey,
    ContourSelection,
    PrerequisiteResult,
    discover_derivative_artifacts,
    discover_raw_xct_images,
    case_keys_match,
    preferred_contours,
    prerequisite_status,
)
from .discovery import discover_manifests, find_records
from .layout import derivative_family_root, manifest_path, record_output_path, voi_token
from .manifest import DerivativeManifest, read_manifest, write_manifest
from .naming import (
    NamingRow,
    RenamePlan,
    apply_naming_row_overrides,
    build_naming_rows,
    build_rename_plan,
    execute_rename_plan,
    read_rename_manifest,
    split_identity_metadata,
    suggested_filename,
    suggested_mids_relative_path,
    suggested_mids_relative_paths,
    undo_rename_manifest,
)
from .planning import WorkflowPlan, WorkflowRequirement, resolve_workflow_plan
from .progress import DerivativeProgressEvent, format_progress_event, parse_progress_event
from .profile_registry import (
    ProfileRecord,
    default_profile_root,
    delete_profile,
    list_profiles,
    load_profile_payload,
    register_profile_asset,
    save_json_profile,
    tool_profile_dir,
)
from .records import DerivativeRecord
from .artifacts import (
    ArtifactIndex,
    ArtifactRecord,
    apply_overrides,
    discover_artifacts,
    normalize_role,
    normalize_session_id,
    normalize_site,
    normalize_subject_id,
    site_category,
)

__all__ = [
    "ArtifactIndex",
    "ArtifactRecord",
    "BatchArtifact",
    "CaseKey",
    "ContourSelection",
    "DerivativeManifest",
    "DerivativeProgressEvent",
    "DerivativeRecord",
    "PrerequisiteResult",
    "ProfileRecord",
    "NamingRow",
    "RenamePlan",
    "WorkflowPlan",
    "WorkflowRequirement",
    "apply_naming_row_overrides",
    "build_naming_rows",
    "build_rename_plan",
    "case_keys_match",
    "default_profile_root",
    "delete_profile",
    "derivative_family_root",
    "discover_artifacts",
    "discover_derivative_artifacts",
    "discover_legacy_registered_microarchitecture_records",
    "discover_legacy_timelapsed_records",
    "discover_manifests",
    "discover_raw_xct_images",
    "execute_rename_plan",
    "find_records",
    "format_progress_event",
    "list_profiles",
    "load_profile_payload",
    "manifest_path",
    "normalize_role",
    "normalize_session_id",
    "normalize_site",
    "normalize_subject_id",
    "parse_progress_event",
    "preferred_contours",
    "prerequisite_status",
    "read_manifest",
    "read_rename_manifest",
    "record_output_path",
    "register_profile_asset",
    "resolve_workflow_plan",
    "save_json_profile",
    "suggested_filename",
    "suggested_mids_relative_path",
    "suggested_mids_relative_paths",
    "site_category",
    "split_identity_metadata",
    "tool_profile_dir",
    "undo_rename_manifest",
    "voi_token",
    "write_compatibility_manifest",
    "write_manifest",
]
